### PR TITLE
Added logger to winch files

### PR DESCRIPTION
**Pull request by Sonny6155**

### CODE REVIEW

**Review by met4000 — CHANGES_REQUESTED** [review]
Winch.cpp:12
log.write(::frc::RobotController::GetFPGATime(), 1, io->winch_motors[0]->GetSelectedSensorPosition(0));

Is this building?

**Review by met4000 — APPROVED** [review]

**Comment by met4000** [comment]
@Sonny6155  Assuming it builds, you can merge it

**Comment by Sonny6155** [comment]
God damn it, I still can't pull approved branches without access.

**Comment by met4000** [comment]
You want me to merge - are you unable to even after reviewed?

**Comment by met4000** [comment]
@Sonny6155 Added you as collab; you should be able to merge now

**Pull request merged**
